apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redis.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
type: Opaque
stringData:
  REDIS_PASSWORD: {{ .Values.redis.password }}
