apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app-monolitic.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "app-monolitic.labels" . | nindent 4 }}
type: Opaque
data:
  DB_NAME: {{ .Values.database.name | b64enc }}
  DB_USERNAME: {{ .Values.database.username | b64enc }}
  DB_PASSWORD: {{ .Values.database.password | b64enc }}

